import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
       
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-gradient-to-b from-[#64026d] to-[#168dc9]">
      
         
           <div className=" text-8xl font-semibold 
            bg-gradient-to-r bg-clip-text  text-transparent 
            from-[#000000] via-[#511660] to-[#000000]
            animate-text p-12">Riwaj Mainali</div> 
          
          
      </main>
    </>
  );
}
