[package]
name = "GameOfLife"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
console_error_panic_hook = { version = "0.1.7", optional = true }
yew = { version = "0.20.0" }

[lib]
crate-type = ["cdylib", "rlib"]
